{% set name = "gitoxide" %}
{% set version = "0.67.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Byron/gitoxide/archive/gix-v{{ version }}.tar.gz
  sha256: 707e7e059189ab17af6bccb0b2e3e767c2abf8a66e1dc47236836456d6e98c9d

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - openssl

test:
  commands:
    - gix --help
    - ein --help

about:
  home: https://github.com/Byron/gitoxide
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An idiomatic, lean, fast & safe pure Rust implementation of Git
  dev_url: https://github.com/Byron/gitoxide

extra:
  recipe-maintainers:
    - danielnachun
