context:
  version: "0.69.1"

package:
  name: gitoxide
  version: ${{ version }}

source:
  url: https://github.com/Byron/gitoxide/archive/gix-v${{ version }}.tar.gz
  sha256: 829c89ec2a500a8e6c9768edb2ee86b0fc0df6d45705e126f7af21638107fe6d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - gix --help
      - ein --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An idiomatic, lean, fast & safe pure Rust implementation of Git
  homepage: https://github.com/Byron/gitoxide
  repository: https://github.com/Byron/gitoxide

extra:
  recipe-maintainers:
    - danielnachun
