context:
  version: 0.68.0

package:
  name: gitoxide
  version: ${{ version }}

source:
  url: https://github.com/Byron/gitoxide/archive/gix-v${{ version }}.tar.gz
  sha256: 5ba97467f8d4e5b2776775686731cbb2a2aea0db95c1d23ceb6ad7e80a25af4d

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - gix --help
      - ein --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An idiomatic, lean, fast & safe pure Rust implementation of Git
  homepage: https://github.com/Byron/gitoxide
  repository: https://github.com/Byron/gitoxide

extra:
  recipe-maintainers:
    - danielnachun
