context:
  version: "0.70.0"

package:
  name: gitoxide
  version: ${{ version }}

source:
  url: https://github.com/Byron/gitoxide/archive/gix-v${{ version }}.tar.gz
  sha256: 111d088c71a35381eee51bbc23ae249917ef414dd7cd692dc5041d47dc2e00e8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - gix --help
      - ein --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An idiomatic, lean, fast & safe pure Rust implementation of Git
  homepage: https://github.com/Byron/gitoxide
  repository: https://github.com/Byron/gitoxide

extra:
  recipe-maintainers:
    - danielnachun
